import json
from datetime import datetime
from typing import Dict, Generator
from binance.client import Client
from datetime import datetime, timedelta


from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteRecordMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    Status,
    Type,
)
from airbyte_cdk.sources import Source

# Defining binance Api
client = Client()

#Get Binance Crypto symbols
prices = client.get_all_tickers()
cryptos = [prices[i]['symbol']  for i in range(len(prices)) if prices[i]['symbol'].endswith('USDT')]
premium_crypto = ['BTCUSDT', 'ETHUSDT', 'BNBUSDT']

def get_ohlcv_inter(crypto, granularity):
    
# Defining start and end time

        start = datetime.today() - timedelta(days=1)
        start = str(start).split(' ')[0]
        end = str(datetime.now()).split(' ')[0]

        hist = client.get_historical_klines(crypto, granularity, start_str = start, end_str = end)
        
        # Formatting data as JSON
        my_json_string = {'history': hist}
        data =  [{"open_time": hist[i][0],
                          "open": hist[i][1], 
                          "high": hist[i][2], 
                          "low":hist[i][3], 
                          "close": hist[i][4], 
                          "close_time": hist[i][5], 
                          "quote_asset_volume": hist[i][6], 
                          "crypto": crypto,
                          "granularity": granularity} 
               for i in range(0,len(hist) - 1)] # Getting data from 00H00 to 23H55

        return data

def get_ohlcv(crypto):
  if(crypto in premium_crypto):
    return get_ohlcv_inter(crypto, '5m')
  
  return get_ohlcv_inter(crypto, '1d')

def get_all_ohlcv():
  data = []
  for crypto in cryptos:
    data = data + get_ohlcv(crypto)
  return {"data": data}


class SourceBinance(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the integration
            e.g: if a provided Stripe API token can be used to connect to the Stripe API.
        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.json file
        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        try:
            # Not Implemented

            return AirbyteConnectionStatus(status=Status.SUCCEEDED)
        except Exception as e:
            return AirbyteConnectionStatus(status=Status.FAILED, message=f"An exception occurred: {str(e)}")

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        """
        Returns an AirbyteCatalog representing the available streams and fields in this integration.
        For example, given valid credentials to a Postgres database,
        returns an Airbyte catalog where each postgres table is a stream, and each table column is a field.
        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.json file
        :return: AirbyteCatalog is an object describing a list of all available streams in this source.
            A stream is an AirbyteStream object that includes:
            - its stream name (or table name in the case of Postgres)
            - json_schema providing the specifications of expected schema for this stream (a list of columns described
            by their names and types)
        """
        streams = []

        stream_name = "TableName"  # Example
        json_schema = {  # Example
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {"columnName": {"type": "string"}},
        }

        # Not Implemented

        streams.append(AirbyteStream(name=stream_name, json_schema=json_schema))
        return AirbyteCatalog(streams=streams)

    def read(
        self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: Dict[str, any]
    ) -> Generator[AirbyteMessage, None, None]:
        """
        Returns a generator of the AirbyteMessages generated by reading the source with the given configuration,
        catalog, and state.
        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
            the properties of the spec.json file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as AirbyteCatalog
            returned by discover(), but
        in addition, it's been configured in the UI! For each particular stream and field, there may have been provided
        with extra modifications such as: filtering streams and/or columns out, renaming some entities, etc
        :param state: When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
            replication in the future from that saved checkpoint.
            This is the object that is provided with state from previous runs and avoid replicating the entire set of
            data everytime.
        :return: A generator that produces a stream of AirbyteRecordMessage contained in AirbyteMessage object.
        """
        stream_name = "TableName" 

        data=get_all_ohlcv()

        # Airbyte message with data 
        yield AirbyteMessage(
            type=Type.RECORD,
            record=AirbyteRecordMessage(stream=stream_name, data=data, emitted_at=int(datetime.now().timestamp()) * 1000),
        )
